version: '3'
services:
    db:
        build: ./db
        container_name: zip2000_db
        hostname: zip2000_db
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: zip2000_app
            MYSQL_USER: zip2000_user
            MYSQL_PASSWORD: zip2000_pass
        volumes:
            - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    node:
        build: ./node
        container_name: zip2000_node
        hostname: zip2000_node
        ports:
            - "5000:5000"
        links:
            - db
        depends_on:
            - db
    web:
        build: ./web
        container_name: zip2000_web
        hostname: zip2000_web
        ports:
            - "8080:80"
        links:
            - node
            - db
        depends_on:
            - node
            - db
        volumes:
            - ./web/src:/var/www/html
